# -*- coding: utf-8 -*-
"""Image Data Augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvW4pFo2hTAYEZpyc5_wyP5DZw4VsFoS
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf
import random

dataset_path = '/content/drive/MyDrive/Colab Notebooks/flower-recognition/flowers/flowers'

os.path.exists(dataset_path)

flower_names = os.listdir(dataset_path)
print(flower_names)

plt.figure(figsize=(20,50))

first_flower_dir = os.path.join(dataset_path, flower_names[0])

image_files = [f for f in os.listdir(first_flower_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]


num_images_to_display = min(50, len(image_files))

if num_images_to_display > 0:
    for i in range(num_images_to_display):
        plt.subplot(10,5,i+1)
        image_path = os.path.join(first_flower_dir, image_files[i])
        img = Image.open(image_path)
        plt.imshow(img)
        plt.axis('off')
    plt.suptitle('Images Before Preprocessing')
    plt.tight_layout()
    plt.show()
else:
    print("No images found to display in the first flower category.")

def preprocess_image(dataset_path, image_size=150):
  images = []
  labels = []
  flowers = []
  image_info = []

  for flower_id, flower_name in enumerate(flower_names):
    flower_class_path = os.path.join(dataset_path, flower_name)


    image_files = []
    for file in os.listdir(flower_class_path):
      if file.lower().endswith(('.png', '.jpg', '.jpeg')):
        image_files.append(file)


    print(f"Total Images Found in {flower_name} : {len(image_files)}")

    for image_name in image_files:
      image_path = os.path.join(flower_class_path, image_name)
      image = Image.open(image_path)
      image = image.resize((image_size, image_size))
      image = image.convert('RGB')
      image = np.array(image) / 255
      images.append(image)
      labels.append(flower_id)

      info = {
          'filename' : image_name,
          'flower_name' : flower_name,
          'flower_id' : flower_id,
          'image_size ' : f"({image.shape[0]} * {image.shape[1]})",


      }
      image_info.append(info)

  images = np.array(images)


  labels = np.array(labels)

  data = pd.DataFrame(image_info)
  data.to_csv('image_info.csv', index=False)


  return images, labels, flower_names



X, y, flower_classes_name = preprocess_image(dataset_path, image_size=150)

"""**Creating DataFrame Using Pandas**"""

df = pd.read_csv('image_info.csv')
df.head()

df.tail()

plt.figure(figsize=(20,50))
for i in range(50):
  plt.subplot(10,5,i+1)
  plt.imshow(X[i])
  plt.axis('off')
plt.suptitle("Image After Preprocessing",fontsize=30)
plt.tight_layout()
plt.show()

"""**Applying Augmentation**"""

os.makedirs('augmented_dataset', exist_ok=True)
os.makedirs('augmented_labels', exist_ok=True)

total_augmented = 0

def apply_augmentations(img_tensor):
    augmented_versions = []


    augmented_versions.append(img_tensor)

    augmented_versions.append(tf.image.flip_left_right(img_tensor))


    augmented_versions.append(tf.image.flip_up_down(img_tensor))

    if img_tensor.shape[-1] == 3:
        gray = tf.image.rgb_to_grayscale(img_tensor)
        gray = tf.image.grayscale_to_rgb(gray)  # convert back to 3 channels
        augmented_versions.append(gray)

    augmented_versions.append(tf.image.rot90(img_tensor))

    augmented_versions.append(tf.image.adjust_brightness(img_tensor, 0.3))

    return augmented_versions


for i in range(len(X)):
    try:

        img = X[i]


        if img.max() > 1.0:
            img = img / 255.0

        label = y[i]

        img_tensor = tf.convert_to_tensor(img, dtype=tf.float32)


        img_tensor = tf.clip_by_value(img_tensor, 0, 1)


        aug_versions = apply_augmentations(img_tensor)

        for j, aug_img in enumerate(aug_versions):

            aug_img = tf.clip_by_value(aug_img, 0, 1)
            np.save(f'augmented_dataset/img_{i}_{j}.npy', aug_img.numpy())
            np.save(f'augmented_labels/label_{i}_{j}.npy', label)
            total_augmented += 1

        if (i+1) % 10 == 0:
            print(f"Processed {i+1}/{len(X)} original images, Created {total_augmented} augmented images")

    except Exception as e:
        print(f"Error on image {i}: {e}")
        continue

print(f"Done! Total augmented images saved: {total_augmented}")